version: "3.8"
name: "aims"

services:
  aims_angular:
    build: "."

    image: aims_angular
    container_name: angular
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
      - PORT=4200
