version: "3.8"
name: "aims"

services:
  web-app:
    build: "."

    image: aims_web_app
    container_name: web_app
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
      - PORT=4200
